version: '3.7'

services:
  postgresql:
    build: ./
    container_name: postgresql
    restart: on-failure
    env_file:
      - .env
#    environment:
#      PG_USER : ${PG_USER}
#      PG_HOST : ${PG_HOST}
#      PG_PORT : ${PG_PORT}
#      PG_PASSWORD : ${PG_PASSWORD}
#      PG_DATABASE : ${PG_DATABASE}
    init : true
    networks:
      - my_network
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - .env
#      POSTGRESQL_PASS : ${POSTGRESQL_PASS}
#      DB_NAME : ${DB_NAME}
#      PMA_HOST : ${PMA_HOST}
#      PMA_PORT : ${PMA_PORT}
#      PGADMIN_DEFAULT_EMAIL : ${PGADMIN_DEFAULT_EMAIL}
#      PGADMIN_DEFAULT_PASSWORD : ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

